# Generated by Django 3.1.7 on 2021-12-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='case_num',
            field=models.IntegerField(default=0, verbose_name='用例数量'),
        ),
        migrations.AlterField(
            model_name='project',
            name='jk_num',
            field=models.IntegerField(default=0, verbose_name='接口数量'),
        ),
    ]
