# Generated by Django 3.1.7 on 2021-12-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0003_modelse'),
    ]

    operations = [
        migrations.CreateModel(
            name='caseapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='接口名称')),
                ('remark', models.CharField(default='', max_length=1000, verbose_name='备注')),
                ('priority', models.CharField(max_length=100, verbose_name='优先级')),
                ('mokuai', models.CharField(max_length=300, verbose_name='所属模块')),
                ('tag', models.CharField(max_length=200, verbose_name='所属标签')),
                ('url', models.CharField(max_length=300, verbose_name='URL')),
                ('methods', models.CharField(max_length=100, verbose_name='请求方法')),
                ('bodys', models.CharField(default=None, max_length=1000, verbose_name='body')),
                ('headers', models.CharField(default=None, max_length=1000, verbose_name='headers')),
                ('cookie', models.CharField(default=None, max_length=1000, verbose_name='cookie')),
                ('resultPk', models.CharField(default=None, max_length=1000, verbose_name='验证字段')),
            ],
            options={
                'db_table': 'caseapi',
            },
        ),
    ]
