# Generated by Django 3.1.7 on 2021-12-30 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0004_caseapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseapi',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caseapi',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='caseapi',
            name='user',
            field=models.CharField(default='', max_length=300, verbose_name='添加人员'),
        ),
    ]
