# Generated by Django 3.1.7 on 2022-01-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0006_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='任务名称')),
                ('id_list', models.CharField(max_length=300, verbose_name='用例id')),
                ('api_num', models.IntegerField(verbose_name='接口数量')),
                ('case_num', models.IntegerField(verbose_name='用例数量')),
                ('status', models.CharField(max_length=200, verbose_name='执行状态')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
