# Generated by Django 3.1.7 on 2022-01-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0009_task_updatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='zx_num',
            field=models.IntegerField(default=1, verbose_name='执行次数'),
            preserve_default=False,
        ),
    ]
