# Generated by Django 3.1.7 on 2022-01-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0010_task_zx_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseapi',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
