# Generated by Django 3.1.7 on 2022-01-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0011_auto_20220104_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reportId', models.CharField(max_length=100, verbose_name='关联报告id')),
                ('name', models.CharField(max_length=300, verbose_name='用例名称')),
                ('result', models.CharField(max_length=300, verbose_name='结果')),
                ('msg', models.CharField(max_length=500, verbose_name='详情')),
                ('caseid', models.CharField(max_length=100, verbose_name='接口id')),
            ],
            options={
                'db_table': 'CaseResult',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('zx_user', models.CharField(max_length=200, verbose_name='执行者')),
                ('taskId', models.CharField(max_length=100, verbose_name='关联任务id')),
                ('api_num', models.IntegerField(verbose_name='接口数量')),
                ('case_num', models.IntegerField(verbose_name='用例数量')),
                ('true_num', models.IntegerField(verbose_name='正确数')),
                ('false_num', models.IntegerField(verbose_name='错误数')),
                ('accuracy', models.CharField(max_length=100, verbose_name='正确率')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'Report',
            },
        ),
    ]
