# Generated by Django 3.1.7 on 2022-01-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0012_caseresult_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='num',
            field=models.IntegerField(default=0, verbose_name='总数量'),
            preserve_default=False,
        ),
    ]
