# Generated by Django 3.1.7 on 2022-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0014_auto_20220106_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseresult',
            name='res',
            field=models.CharField(default=1, max_length=2000, verbose_name='response'),
            preserve_default=False,
        ),
    ]
