# Generated by Django 3.1.7 on 2022-01-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0015_caseresult_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresult',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
