# Generated by Django 3.1.7 on 2022-01-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0018_schedlermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedlermodel',
            name='funcName',
            field=models.CharField(default=1, max_length=300, verbose_name='方法名称'),
            preserve_default=False,
        ),
    ]
