# Generated by Django 3.1.7 on 2022-01-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0020_task_cron'),
    ]

    operations = [
        migrations.CreateModel(
            name='logCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caseid', models.IntegerField(verbose_name='caseid')),
                ('runCaseNumId', models.IntegerField(verbose_name='运行次数id')),
                ('msg', models.CharField(max_length=1000, verbose_name='执行日志内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'logCase',
            },
        ),
    ]
