# Generated by Django 3.1.7 on 2022-01-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0021_logcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseapi',
            name='runCaseNum',
            field=models.IntegerField(default=1, verbose_name='接口运行次数统计'),
            preserve_default=False,
        ),
    ]
