# Generated by Django 3.1.7 on 2022-01-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0022_caseapi_runcasenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseapi',
            name='runCaseNum',
            field=models.IntegerField(default=0, verbose_name='接口运行次数统计'),
        ),
    ]
