# Generated by Django 3.1.7 on 2022-01-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0023_auto_20220111_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accuracy',
            field=models.CharField(default=0, max_length=200, verbose_name='最新的正确率'),
            preserve_default=False,
        ),
    ]
