# Generated by Django 3.1.7 on 2022-01-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0024_task_accuracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=500, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=500, verbose_name='密码')),
                ('token', models.CharField(max_length=1000, verbose_name='Token')),
                ('role', models.CharField(default=0, max_length=500, verbose_name='角色')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
