# Generated by Django 3.1.7 on 2022-01-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0025_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiangmu', models.IntegerField(verbose_name='项目数')),
                ('mokuai', models.IntegerField(verbose_name='模块数')),
                ('taskNum', models.IntegerField(verbose_name='任务数量')),
                ('taskexecute', models.IntegerField(verbose_name='任务执行次数')),
                ('taskdingshi', models.IntegerField(verbose_name='任务执行定时次数')),
                ('apiNum', models.IntegerField(verbose_name='接口数量')),
                ('caseNum', models.IntegerField(verbose_name='用例数量')),
            ],
            options={
                'db_table': 'num',
            },
        ),
    ]
