# Generated by Django 3.1.7 on 2022-01-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0026_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='expend_time',
            field=models.CharField(default=0, max_length=100, verbose_name='消耗时间'),
        ),
    ]
