# Generated by Django 3.1.7 on 2022-01-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0027_report_expend_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='zx_time',
            field=models.CharField(default=0, max_length=300, verbose_name='执行时间'),
        ),
    ]
