# Generated by Django 3.1.7 on 2022-01-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0029_auto_20220118_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='makeUser',
            field=models.CharField(default='', max_length=200, verbose_name='创建者'),
        ),
    ]
