# Generated by Django 3.1.7 on 2022-01-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0030_task_makeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='end_time',
            field=models.CharField(default='', max_length=200, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='report',
            name='start_time',
            field=models.CharField(default='', max_length=200, verbose_name='开始时间'),
        ),
    ]
