# Generated by Django 3.1.7 on 2022-01-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0033_gloadconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='gloadCaseKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.CharField(max_length=100, verbose_name='caseid')),
                ('keyRule', models.CharField(max_length=200, verbose_name='提取规则')),
                ('keyName', models.CharField(max_length=200, verbose_name='赋值参数')),
                ('values', models.CharField(max_length=1000, verbose_name='提取值')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'gloadCaseKey',
            },
        ),
    ]
