# Generated by Django 3.1.7 on 2022-01-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0034_gloadcasekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseresult',
            name='expent_time',
            field=models.CharField(default=1, max_length=300, verbose_name='消耗时间'),
            preserve_default=False,
        ),
    ]
