# Generated by Django 3.1.7 on 2022-01-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0035_caseresult_expent_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='环境名称')),
                ('envId', models.CharField(max_length=100, verbose_name='环境ID')),
                ('urlName', models.CharField(max_length=300, verbose_name='域名')),
                ('ip', models.CharField(max_length=200, verbose_name='ip')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'environment',
            },
        ),
    ]
