# Generated by Django 3.1.7 on 2022-01-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0038_auto_20220124_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloadcasekey',
            name='env',
            field=models.CharField(default='', max_length=100, verbose_name='执行环境'),
        ),
    ]
