# Generated by Django 3.1.7 on 2022-01-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0039_gloadcasekey_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseapi',
            name='extractor',
            field=models.CharField(default='', max_length=1000, verbose_name='提取器'),
        ),
    ]
